= Ubuntu server ISO generator

== What is this?

The `genIso.sh` script generates an up-to-date and patched Ubuntu Bionic
server ISO that configures some basic security settings after first boot using
a systemd service.

The security configuration is based on https://github.com/konstruktoid/hardening[konstruktoid/hardening].

NOTE: This is problably not the prettiest way of doing it, but it shows the
basics of modifying and generating a ISO.

== How do I use it?

Download the repository with `git clone https://github.com/konstruktoid/hardening-geniso`,
run `sudo bash genISO.sh` in the `hardening-geniso` directory.

If nothing bad happens, an ISO and a `SHA256SUM` file should be present in the
`~/custom-img/` directory.

== Structure

[source,shell]
----
.
├── README.adoc
├── SHA256SUM
├── VBoxUbuntuTesting.sh
├── Vagrantfile
├── config
│   ├── config.sh
│   ├── hardening-config.service
│   ├── sysctl.conf
│   └── tmp.mount
└── genISO.sh

1 directory, 9 files
----

== Test automation using VirtualBox

Running `bash ./VBoxUbuntuTesting.sh` will use https://www.virtualbox.org/[VirtualBox]
to run an available ISO on virtual machines configured with `BIOS`, `EFI`
and `EFI64` firmware.
