packer {
  required_version = "~> 1.16.0"

  required_plugins {
    qemu = {
      version = "~> 1.1.6"
      source  = "github.com/hashicorp/qemu"
    }
  }
}

variable "iso_url" {
  type        = string
  default     = "https://cloud-images.ubuntu.com/resolute/current/resolute-server-cloudimg-amd64.img"
  description = "Ubuntu cloud image used as the base disk. Point this at another release directory to build a different release."
}

variable "iso_checksum" {
  type        = string
  default     = "sha256:8196be9d7958059cb56c6c75c80fdf6cee8a8885bc149ea791d7db1c7ef93035"
  description = "Checksum of iso_url, from the SHA256SUMS file next to it. current/ is republished daily, so this needs refreshing whenever the upstream image changes."
}

variable "release_version" {
  type        = string
  default     = "26.04"
  description = "Ubuntu release version of var.iso_url, used to name the output image."
}

variable "disk_size" {
  type        = string
  default     = "20000M"
  description = "Disk size of the built image."
}

variable "memory" {
  type        = number
  default     = 2048
  description = "Memory, in MB, given to the build VM."
}

variable "cpus" {
  type        = number
  default     = 2
  description = "Number of CPUs given to the build VM."
}

variable "headless" {
  type        = bool
  default     = true
  description = "Run the build VM without a GUI."
}

variable "accelerator" {
  type        = string
  default     = "kvm"
  description = "QEMU accelerator to use."
}

variable "qemu_efi_firmware_code" {
  type        = string
  default     = "/usr/share/OVMF/OVMF_CODE_4M.fd"
  description = "Read-only UEFI firmware used to boot the build VM."
}

variable "qemu_efi_firmware_vars" {
  type        = string
  default     = "/usr/share/OVMF/OVMF_VARS_4M.fd"
  description = "Writable UEFI variable store template used to boot the build VM."
}

variable "hardening_role_version" {
  type        = string
  default     = "v4.4.1"
  description = "Tag of konstruktoid/ansible-role-hardening to provision with. Must match the version pinned in config/local.yml."
}

variable "syft_version" {
  type        = string
  default     = "v1.46.0"
  description = "Tag of anchore/syft used to generate the SBOM."
}

variable "username" {
  type        = string
  default     = "ubuntu"
  description = "Login and SSH username configured by cloud-init."
}

variable "password" {
  type        = string
  default     = "ubuntu"
  sensitive   = true
  description = "Plaintext login password for var.username, used to authenticate sudo during provisioning."

  validation {
    condition     = can(regex("^[A-Za-z0-9_@%+=:,./-]+$", var.password))
    error_message = "The password variable must only contain [A-Za-z0-9_@%+=:,./-]; other characters break the single-quoted shell values it is passed through."
  }
}

variable "password_hash" {
  type        = string
  default     = "$6$2GvGHZprsvH/AWjF$cYTR/lA/FudhHo/SF2iKs4yPQ3t5QdMWmbtg3ZeOlkgStgR/zYb7O7Q/79pfJKQ9DtEwaJ8V4i3pNXlrKlU310"
  sensitive   = true
  description = "SHA512 hash of var.password, generated with `openssl passwd -6`. Must correspond to var.password."
}

variable "ssh_public_key_file" {
  type        = string
  description = "Public half of the ephemeral keypair generated by build_box.sh, added to authorized_keys so Packer can provision over SSH."
}

variable "ssh_private_key_file" {
  type        = string
  description = "Private half of the ephemeral keypair generated by build_box.sh, used by Packer to connect over SSH."
}

variable "ssh_authorized_keys" {
  type        = list(string)
  default     = []
  description = "Additional public keys to keep in authorized_keys after the build. The build-only ephemeral key is stripped by scripts/cleanup.sh."
}

locals {
  timestamp     = regex_replace(timestamp(), "[- TZ:]", "")
  image_name    = "ubuntu-${var.release_version}-x86_64-${local.timestamp}"
  output_dir    = "${path.root}/output"
  build_dir     = "${path.root}/output/${local.image_name}"
  build_pub_key = trimspace(file(var.ssh_public_key_file))

  sudo_command = ". {{ .EnvVarFile }}; echo \"$SUDO_PASSWORD\" | sudo -S --preserve-env=BUILD_USERNAME,HARDENING_ROLE_VERSION,POWEROFF_AFTER_CLEANUP,SYFT_VERSION bash -eux -o pipefail '{{ .Path }}'"

  provisioner_env = [
    "BUILD_USERNAME=${var.username}",
    "HARDENING_ROLE_VERSION=${var.hardening_role_version}",
    "POWEROFF_AFTER_CLEANUP=true",
    "SUDO_PASSWORD=${var.password}",
    "SYFT_VERSION=${var.syft_version}",
  ]
}

source "qemu" "hardened" {
  iso_url          = var.iso_url
  iso_checksum     = var.iso_checksum
  disk_image       = true
  output_directory = local.build_dir
  vm_name          = "${local.image_name}.qcow2"

  disk_size      = var.disk_size
  format         = "qcow2"
  disk_interface = "virtio-scsi"
  net_device     = "virtio-net"

  accelerator = var.accelerator
  memory      = var.memory
  cpus        = var.cpus
  headless    = var.headless

  efi_boot          = true
  efi_firmware_code = var.qemu_efi_firmware_code
  efi_firmware_vars = var.qemu_efi_firmware_vars

  cd_label = "cidata"
  cd_content = {
    "meta-data" = file("${path.root}/seed/meta-data")
    "user-data" = templatefile("${path.root}/seed/user-data.pkrtpl.hcl", {
      hostname             = "ubuntu-hardened"
      username             = var.username
      password_hash        = var.password_hash
      authorized_keys_json = jsonencode(concat([local.build_pub_key], var.ssh_authorized_keys))
    })
  }

  qemuargs = [["-serial", "file:${local.build_dir}/serial.log"]]

  ssh_username         = var.username
  ssh_private_key_file = var.ssh_private_key_file
  ssh_timeout          = "1h"

  # scripts/cleanup.sh arms the poweroff as root, so no password travels the guest command line.
  shutdown_command = "true"
  shutdown_timeout = "15m"
}

build {
  name    = "hardened-qemu"
  sources = ["source.qemu.hardened"]

  provisioner "file" {
    sources     = ["config/ansible.cfg", "config/local.yml", "config/requirements.yml"]
    destination = "/tmp/"
  }

  provisioner "file" {
    content     = join("\n", var.ssh_authorized_keys)
    destination = "/tmp/authorized_keys"
  }

  provisioner "shell" {
    environment_vars  = local.provisioner_env
    execute_command   = local.sudo_command
    use_env_var_file  = true
    expect_disconnect = true
    pause_before      = "10s"
    remote_folder     = "/var/tmp"
    scripts = [
      "${path.root}/scripts/hardening.sh",
      "${path.root}/scripts/sbom.sh",
    ]
  }

  provisioner "file" {
    direction   = "download"
    source      = "/tmp/sbom.spdx.json"
    destination = "${local.build_dir}/${local.image_name}.spdx.json"
  }

  provisioner "file" {
    direction   = "download"
    source      = "/tmp/sbom.cdx.json"
    destination = "${local.build_dir}/${local.image_name}.cdx.json"
  }

  provisioner "shell" {
    environment_vars  = local.provisioner_env
    execute_command   = local.sudo_command
    use_env_var_file  = true
    expect_disconnect = true
    pause_before      = "10s"
    remote_folder     = "/var/tmp"
    scripts           = ["${path.root}/scripts/cleanup.sh"]
  }

  error-cleanup-provisioner "shell" {
    environment_vars  = local.provisioner_env
    execute_command   = local.sudo_command
    use_env_var_file  = true
    expect_disconnect = true
    remote_folder     = "/var/tmp"
    scripts           = ["${path.root}/scripts/cleanup.sh"]
  }
}
