---
- name: Checkout and configure konstruktoid.hardening
  hosts: localhost
  any_errors_fatal: true
  tasks:
    - name: Install git
      become: true
      ansible.builtin.package:
        name: git
        state: present

    - name: Checkout konstruktoid.hardening
      become: true
      ansible.builtin.git:
        repo: https://github.com/konstruktoid/ansible-role-hardening
        dest: /etc/ansible/roles/konstruktoid.hardening
        version: master

    - name: Remove git
      become: true
      ansible.builtin.package:
        name: git
        state: absent

    - name: Include the hardening role
      ansible.builtin.include_role:
        name: konstruktoid.hardening
      vars:
        auditd_apply_audit_rules: false
        block_blacklisted: false
        install_aide: false
        sshd_admin_net:
          - "0.0.0.0/0"
        sshd_allow_groups:
          - ubuntu
          - vagrant
        sshd_allow_users: []
        sshd_login_grace_time: 60
        sshd_max_auth_tries: 10
        sshd_use_dns: "no"
        sshd_permit_root_login: "no"
        suid_sgid_permissions: false
