---
# Keep in sync with konstruktoid.hardening at var.hardening_collection_version.
collections:
  - name: ansible.posix
    version: 2.2.2
    source: https://github.com/ansible-collections/ansible.posix.git
    type: git
  - name: community.crypto
    version: 3.3.0
    source: https://github.com/ansible-collections/community.crypto.git
    type: git
  - name: community.general
    version: 13.3.0
    source: https://github.com/ansible-collections/community.general.git
    type: git
  - name: community.library_inventory_filtering_v1
    version: 1.1.5
    source: https://github.com/ansible-collections/community.library_inventory_filtering.git
    type: git
  - name: konstruktoid.hardening
    version: v0.3.2
    source: https://github.com/konstruktoid/ansible-collection-hardening.git
    type: git
